server:
  port: 5041

spring:
  rabbitmq:
    addresses: localhost
  cloud:
    aws:
      endpoint: http://localhost:19000

powsybl-ws:
  database:
    host: localhost

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080/

gridsuite:
  services:
    filter-server:
      base-uri: http://localhost:5027
    report-server:
      base-uri: http://localhost:5028
    dynamic-simulation-server:
      base-uri: http://localhost:5032
    dynamic-security-analysis-server:
      base-uri: http://localhost:5040
